- name: Clone the application repository
  git:
    repo: 'https://github.com/ajayD1345/DevOps-Stage-4.git'
    dest: /opt/app
    version: main

- name: Start the application with Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/app
